# Uji Numpy

In [2]:
# Sertakan pustaka Numpy untuk seluruh notebook ini
import numpy as np

In [11]:
# Tetapkan suatu larik atau array (semacam matriks)

larik1 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print('Larik pertama =')
print(larik1)

Larik pertama =
[[10 20 30]
 [40 50 60]]


In [5]:
# Tentukan dimensi, ukuran dan bentuk dari larik pertama

dimensi = np.ndim(larik1)
ukuran = np.size(larik1)
bentuk = np.shape(larik1)
print('Dimensi dari larik pertama =', dimensi)
print('Ukuran dari larik pertama  =', ukuran)
print('Bentuk dari larik pertama  =', bentuk)

Dimensi dari larik pertama = 2
Ukuran dari larik pertama  = 6
Bentuk dari larik pertama  = (2, 3)


In [12]:
# Tetapkan larik kedua

larik2 = np.array([
    [15, 25, 35],
    [45, 55, 65]
])
print('Larik kedua =')
print(larik2)

Larik kedua =
[[15 25 35]
 [45 55 65]]


In [13]:
# Jumlah dan selisih dari kedua larik

jumlah = larik1 + larik2
selisih = larik1 - larik2
print('Jumlah kedua larik  =')
print(jumlah)
print('Selisih kedua larik =')
print(selisih)

Jumlah kedua larik  =
[[ 25  45  65]
 [ 85 105 125]]
Selisih kedua larik =
[[-5 -5 -5]
 [-5 -5 -5]]


In [14]:
# Hasil perkalian dan pembagian kedua larik

hasilKali = larik1 * larik2
hasilBagi = larik1 / larik2
print('Hasil perkalian kedua larik =')
print(hasilKali)
print('Hasil pembagian kedua larik =')
print(hasilBagi)

Hasil perkalian kedua larik =
[[ 150  500 1050]
 [1800 2750 3900]]
Hasil pembagian kedua larik =
[[0.66666667 0.8        0.85714286]
 [0.88888889 0.90909091 0.92307692]]


In [15]:
# Hasil pembagian-bulat dan sisa-bagi dari kedua larik

hasilBagiBulat = larik2 // larik1
sisaBagiBulat = larik2 % larik1
print('Hasil pembagian-bulat kedua larik =')
print(hasilBagiBulat)
print('Sisa pembagian-bulat kedua larik =')
print(sisaBagiBulat)

Hasil pembagian-bulat kedua larik =
[[1 1 1]
 [1 1 1]]
Sisa pembagian-bulat kedua larik =
[[5 5 5]
 [5 5 5]]


In [16]:
# Hasil kuadrat dan akar-pangkat-dua dari kedua larik

hasilKuadrat = larik1 ** 2
akarPangkat2 = larik2 ** 0.5
print('Hasil pangkat-dua dari larik pertama =')
print(hasilKuadrat)
print('Hasil akar-pangkat-dua dari larik kedua =')
print(akarPangkat2)

Hasil pangkat-dua dari larik pertama =
[[ 100  400  900]
 [1600 2500 3600]]
Hasil akar-pangkat-dua dari larik kedua =
[[3.87298335 5.         5.91607978]
 [6.70820393 7.41619849 8.06225775]]
